name: money_planet
description: "KGU Capstone Project - Money Planet"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.0.0
  intl: ^0.20.2
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.1.2
  http: ^1.3.0
  google_mlkit_text_recognition: ^0.15.0
  path_provider: ^2.1.5
  fl_chart: ^0.71.0
  flutter_tesseract_ocr: ^0.4.28
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"  # 아이콘 경로
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff" # 배경색
  image: "assets/images/splash_image.png" # 중앙에 표시할 이미지
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

#   이미지 등록
  assets:
    - assets/images/test.JPG

    - assets/images/icons/bell_01.png
    - assets/images/icons/help_circle.png
    - assets/images/icons/category_car.png
    - assets/images/icons/category_coffee.png
    - assets/images/icons/category_food.png
    - assets/images/icons/category_health.png
    - assets/images/icons/category_life.png
    - assets/images/icons/category_rest.png
    - assets/images/icons/category_shopping.png
    - assets/images/icons/category_culture.png
    - assets/images/icons/category_education.png
    - assets/images/icons/category_event.png
    - assets/images/icons/category_fashion.png
    - assets/images/icons/category_home.png
    - assets/images/icons/category_mart.png
    - assets/images/icons/category_pet.png
    - assets/images/icons/category_saving.png
    - assets/images/icons/category_tax.png
    - assets/images/icons/pencil_line.png
    - assets/images/icons/arrow_square_downright.png
    - assets/images/icons/arrow_square_upright.png

    - assets/images/planet_icon/MERCURY.png
    - assets/images/planet_icon/VENUS.png
    - assets/images/planet_icon/EARTH.png
    - assets/images/planet_icon/MARS.png
    - assets/images/planet_icon/JUPITER.png
    - assets/images/planet_icon/SATURN.png
    - assets/images/planet_icon/URANUS.png
    - assets/images/planet_icon/NEPTUNE.png
    - assets/images/planet_icon/planet_border.png

    - assets/images/rocket1.png
    - assets/images/rocket3.png
    - assets/images/login_planet.png
    - assets/images/splash_image.png
    - assets/images/app_icon.png

    - assets/images/type_icon/artist_palette.png
    - assets/images/type_icon/crown.png
    - assets/images/type_icon/money_bag.png
    - assets/images/type_icon/objects.png
    - assets/images/type_icon/reading_glasses.png
    - assets/images/type_icon/rocket.png
    - assets/images/type_icon/roller_coaster.png
    - assets/images/type_icon/sparkles.png

    - assets/images/type_icon/type_shopping.png
    - assets/images/type_icon/type_cafe.png
    - assets/images/type_icon/type_food.png

    - assets/
    - assets/tessdata/

  # 폰트 등록
  fonts:
    - family: Soyo
      fonts:
        - asset: assets/fonts/SOYO Maple Regular.ttf

    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700



  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
